### ISSUE TITLE
cannot launch craft to exile harmony on mac[BUG]

### ISSUE THREAD

**Issue by Racoondog21** [mahjerion/Craft-to-Exile-Harmony#87] opened 2021-02-17 21:21 UTC
**Technical Specs (please complete the following information):**
 - Craft to Exile Version 2.0.2d
 - Launcher
 - RAM Allocation [4GB]

**Describe the bug**
craft to exile harmony works fine on my windows PC, but if i try it on my mac laptop (macOS catalina) launching it from the minecraft launcher closes the launcher and does not open up minecraft. (i use curseforge btw)

**To Reproduce**
1. Go to curseforge, select modpack "craft to exile [harmony]“ and press play
2. Then on minecraft launcher checked if correct profile was selected
3. Try to launch minecraft/craft to exile harmony
4. nothing starts launching/loading

**Expected behavior**
Minecraft is supposed to load

**Additional Information (screen shots, etc.)**
i dont know what the problem could be, on my pc it works fine, but some of my friends cant join because they only play on mac and it doesnt work for both of us on mac

**Comment by mahjerion** [comment] 2021-02-17 22:05
The problem is FancyMenu and its dependency. You can remove them to fix the error.

This is fixed for the next harmony update so I'll close this, thanks for reporting!

**Closed by mahjerion** 2021-02-17 22:05 UTC
Labels: bug
